robot:
  pos: [0.0, -0.75, 0.5]
  joint_pos: [1.5, -0.1, 0.0, -1.6, 0.0, 1.6, 0.0]

patient:
  pos: [0.2, -0.45, 1.05]
  euler_yxz: [-90.0, -90.0, 0.0]
  id_list: ['s0010', 's0014', 's0015']
  label_res: 0.0015 # m

bed:
  pos: [0.0, 0.0, 0.3]
  euler_xyz: [90, 0.0, 90]
  scale: 0.001

motion_planning:
  patient_xz_goal: [170, 170, 2.0]
  scale: [[5, 5, 0.1]]

train:
  rand_steps: 100
  num_episodes: 1000
  rand_init_scale: [100, 50, 1.64]
  rand_init_start: [100, 50, 1.5]
  motion_noise_scale: 40

validation:
  val_interval: 5
  rand_init_scale: [60, 30, 1.5]
  rand_init_start: [120, 60, 1.7]

sim:
  episode_length: 500
  max_action: [10, 10, 0.2]
  patient_xz_range: [[70, 100, 1.5], [170, 200, 3.14]]
  patient_xz_init_range: [[100, 50, 1.5], [140, 120, 3.5]]
  if_use_ct: True
  ct_range: [-300, 3000]
  vis_us: True
  vis_seg_map: False