robot:
  pos: [0.0, -0.75, 0.6]
  joint_pos: [1.5, -0.1, 0.0, -1.6, 0.0, 1.6, 0.0]

patient:
  pos: [0.2, -0.45, 1.1]
  euler_yxz: [-90.0, -90.0, 0.0]
  id_list: ['s0010', 's0014', 's0015']
  label_res: 0.0015 # m

bed:
  pos: [0.0, 0.0, 0.3]
  euler_xyz: [90, 0.0, 90]
  scale: 0.001

sim:
  episode_length: 500
  patient_xz_range: [[100, 100, 1.5], [200, 200, 3.14]]
  patient_xz_init: [150, 150, 2.5]
  vis_us: False
  vis_seg_map: False